### PR TITLE
adapt the bot to key persistence

### PR DESCRIPTION
**Pull request by rizar**
Currently generated 6280 demos for the boss level without any failures. Will launch 1000000 overnight (can do it even without merging this PR, so no rush).

Changes:

- (most important) drop the key once you open the door, except if you already had the key when you conceived the idea of going to the door (yeah, it's complicated, but so far it doesn't crash)
- small changes to `make_agent_demos.py`
- delete useless `super().get_action()`
- fix a small typo in `scripts/gui.py`

### CODE REVIEW

**Comment by maximecb** [comment]
Did you run into any more issues, or is this ready to merge?

**Comment by rizar** [comment]
Not sure yet. Will keep you posted.

**Comment by rizar** [comment]
The bot is still crashing sometimes (in less than 0.1% of episodes). I will be looking at it.

**Comment by rizar** [comment]
I think this PR is fine, it's just that it may be not the last issue on our way.  See e.g. #14

**Pull request merged**
