### PR TITLE
New improved bot - Suggesting actions

### PR DESCRIPTION
**Pull request by saleml**
There are plenty of things in this PR:

1. I improved the bot's performance on average

 |  **Level/Bot** | Bot (Old) (success rate ) | Bot (Old) (mean # steps on successful episodes) | Bot (New) (success rate) | Bot (New) (mean # steps)  | **Improvement** |
|  ------ | :------: | ------ | :------: | ------ | ------ |
|  OpenRedDoor | 100% | 4.8 | 100% | 4.8 | 0% |
|  GoToLocal | 100% | 5.63 | 100% | 5.41 | 4% |
|  PutNextLocal | 100% | 11.97 | 100% | 11.97 | 0% |
|  GoToObjMaze | 100% | 70.86 | 100% | 70.86 | 0% |
|  GoTo | 100% | 52.11 | 100% | 52.07 | 0% |
|  Open | 100% | 29.37 | 100% | 29.11 | 1% |
|  Pickup | 100% | 53.27 | 100% | 53.07 | 0% |
|  PickupLoc | 100% | 7.93 | 100% | 6.51 | 18% |
|  PutNext | 100% | 91.28 | 100% | 89.77 | 2% |
|  Unlock | 100% | 96.42 | 100% | 90.94 | 6% |
|  GoToImpUnlock | 100% | 119.35 | 100% | 115.64 | 3% |
|  UnblockPickup | 100% | 55.02 | 100% | 54.8 | 0% |
|  GoToSeq | 100% | 70.39 | 100% | 69.35 | 1% |
|  Synth | 100% | 52.1 | 100% | 51.51 | 1% |
|  SynthLoc | 100% | 47.8 | 100% | 47.67 | 0% |
|  SynthSeq | 98.60% | 84.28 | 100% | 80.97 | 4% |
|  BossLevel | 98.60% | 89.57 | 100% | 86.66 | 3% |
|  BossLevel (2000 more runs) |  | 87.05 | 100% | 83.91 | 4% |
|  **On average** |  | 57.17777777777777 |  | 55.834444444444436 | 2% |

2. The bot can now suggest actions given its internal state, but also update its internal state given external actions (i.e. **advice**)

3. I changed the bot's code to incorporate some Subgoal objects. Makes debugging easier, and is nicer to handle IMO.

4. **Lost functionality**: We don't have the ForgetBot anymore. As we haven't really been using it so far, I didn't prioritize it. It can be incorporated to the new bot later.

5. Base code for DAGGER ! 

Some quick TODOs, that can be done after this is merged:

- Test the bot in 'done action' mode !

- In `eval_bot`, have an option where we evaluate the bot when the action taker != bot (e.g. action taker = bot with proba. 0.8 and random with proba 0.2). The code is available, it just needs to be merged. This would evaluate the quality of out-of-trajectory advice the bot gives.

- For all subgoals, make sure to limit the repetitions in `get_action` and `take_action` when necessary

Some non-quick TODOs:

- Improve the bot by going through the ~20 TODO's in `bot.py`

- Improve the bot by spending some time watching the bot acting in `gui.py` or `enjoy.py` and note scenarios in which you were like "Hum, I wouldn't have done THAT" or "That's so stupid". This should be fun

- Improve the quality of the bot advice by manually sub-optimally (or out-of-bot-trajectory) acting in `gui.py` and checking when the bot advice doesn't make sense

- Bring back the forgetful bot

### CODE REVIEW

**Comment by maximecb** [comment]
@rizar I don't think we care about the forget bot. What say you?

**Comment by rizar** [comment]
The code looks good, but do we have a test for advising capabilities? Automatic verification is really crucial in this case, because there is soooo many corner cases..

**Comment by saleml** [comment]
I added the possibility of making these kinds of tests:
For the X first steps, either pick the action produced by a random agent or a model-based agent (already trained on something) with proba P **or** the optimal bot action with proba 1-P, and for the subsequent steps, let the bot continue and see if the episode can be fixed

2 possible issues can arise in such scenarios:
- The bad agent opens a box -> Throw an error to signal the end of the episode (Ideally one should check if that box is essential to complete the mission, but this is an additional burden that we don't really need right now)
- The bad agent does a lot of bad things (moving objects around for no reason) that the bot would need to fix before completing the actual mission -> Bot runs out of time (max steps). But this is essentially a problem of how advise is given: Should the bot fix everything wrong the bad agent did ? Currently the answer is yes, but the advise can be more useful otherwise.

**Comment by maximecb** [comment]
I would say, maybe keep things simple, and only do random turning and movement actions, or opening doors, actions that are not irreversible.

**Comment by saleml** [comment]
Do you prefer it like this ? 
I just added a quick hack to make the RandomAgent use actions in (left, right, forward) and toggle if forward cell is a door. It's simpler to implement this way rather than modifying the act function of RandomAgent (given that it uses an ACModel).
-> No need to have Disappeard Box erros, and no lengthy episode failures

**Comment by maximecb** [comment]
Simpler is better. I would have preferred that the code be separated between normal bot testing and advising, but this is ok.

Two questions/comments
- You set `bad_action_proba` to 1 by default. Isn't that high? Does the bot ever take over?
- In general, if you need to set a seed on a random generator (eg: `np.random.seed`), I think it's better to create your own private RNG and seed it. This is because other parts of the code might also seed the RNG. It just seems like safer practice to have local instances IMO.

**Comment by saleml** [comment]
There would be a lot of similar lines of codes if we were to separate normal bot testing and advising.

The bot takes over after `non_optimal_steps` steps. Which is `len(episode)/3` by default. The `bad_action_proba` only govrens the first `non_optimal_steps` steps.

I can make it simpler, by avoiding the option of having bad_action_proba < 1, and always play the non-optimal actions initially (there would be no need for any RNG in this case)

**Comment by maximecb** [comment]
I think it would be best to use a local RNG. 

It might also be beter if RandomAgent use its own private RNG and uniformly random actions? Using a randomly initialized model, always with the same seed, means the actions could be biased in some specific way. I think we might get better testing with uniformly random actions.

**Comment by saleml** [comment]
Should be better now. RandomAgent is simply instantiates a rng now.

Do you see a better way to only allow random left/right/fwd moves, and opening of doors ?

**Comment by maximecb** [comment]
Rejection sampling seems like the best solution 👍

**Comment by maximecb** [comment]
I guess the last thing to do would be to add a command to the automated tests to run `eval_bot` and check that the bot successfully advises on some number of runs. Say, 50 runs of BossLevel, assuming that can run quickly (less than 30s):

https://github.com/mila-udem/babyai/blob/master/.travis.yml#L25

After that, I think we're ready to merge?

**Comment by saleml** [comment]
Should be good to go now.
P.S. : I don't know if it's a bug or a feature, but I just realized that BossLevel(seed x) = SynthSeq(seed x) if we don't look at instructions. And when the instruction of BossLevel(seed x) has no ImpUnlock, then both instructions are the same.

**Comment by maximecb** [comment]
There should be some boss levels with a locked room, while the synthseq levels should have no locked room.

**Comment by maximecb** [comment]
Thanks for taking the time to complete and test the bot Salem.

**Comment by saleml** [comment]
> the synthseq levels should have no locked room.
They do, but they aren't necessary to solve the mission. 
Basically what I'm saying is that for a seed X, the environment corresponding to BossLevel(seed X) is the same as the one corresponding to SynthSeq(Seed X), but the instructions are different when BossLevel requires ImpUnlock

**Comment by maximecb** [comment]
Ok, I will look into it :+1:

**Pull request merged**
