### PR TITLE
bot v2

### PR DESCRIPTION
**Pull request by saleml**
This PR **significantly improves the bot (see results below)**. If the modifications added to the bot/verifier in this PR are merged, I can go ahead with another PR with the BotAdvisor, given that the logic is the same. We would need to decide if we want to keep both bots or not, probably depending on how much code sharing VS copy pasting there would be between the two of them.
Main additions:
- The verifier has in its internal memory a "state" of the environment initially, that is used to verify instructions. I modified the `step` function to make the verifier update this state every-time the `drop` action is played. This has the benefit of tracking objects when they are moved. One important consequence is for `PutNext` instructions (Put A next to B): If for some reason you move B (it was blocking the road, or you just want to because why not), you would need to put A next to the new position of B, and not next to its initial position.
- This requires additional validations of the environments. We don't want scenarios in which you need to "Put A next to B" where A is a key that should be used to open a door that leads to the room containing B (or similar scenarios).
- The shortest path function is modified into taking into account the steps necessary to reach a certain point, instead of the number of cells in between.
- Looking for a shortest path with blockers has been improved in order to avoid scenarios where the bot removes a random object on the way to the target even if it's not a blocker per se.
- And a few more things...

~~I would fix the TODOs before merging this (especially the one in https://github.com/mila-udem/babyai/pull/1/files#diff-23560fa0078a677e0990569da3602cd5R374). If you have ideas of how to do this quickly I'm all ears.~~

**Can the bot be improved?**: Definitely. This is not optimal at all.
**How?**: Use `enjoy.py` or `gui.py` and look for scenarios where you think the bot acted sub-optimally. I'd be happy to look at those. Just provide me the level and the seed.

**Performance comparison on 500 runs**

|  **Level/Bot** | Bot (Old) success rate | Bot (Old) mean # steps on successful episodes | Bot (New) success rate  | Bot (New) mean # steps | **Improvement** |
|  ------ | :------: | ------ | :------: | ------ | ------ |
|  OpenRedDoor | 100% | 5.13 | 100% | 4.8 | 6% |
|  GoToLocal | 100% | 6.58 | 100% | 5.63 | 14% |
|  PutNextLocal | 100% | 13.76 | 100% | 11.97 | 13% |
|  GoToObjMaze | 100% | 91.21 | 100% | 70.86 | 22% |
|  GoTo | 100% | 68.86 | 100% | 52.11 | 24% |
|  Open | 100% | 39.74 | 100% | 29.37 | 26% |
|  Pickup | 100% | 70.05 | 100% | 53.27 | 24% |
|  PickupLoc | 100% | 8.61 | 100% | 7.93 | 8% |
|  PutNext | 100% | 116.96 | 100% | 91.28 | 22% |
|  Unlock | 100% | 123.31 | 100% | 96.42 | 22% |
|  GoToImpUnlock | 100% | 149.99 | 100% | 119.35 | 20% |
|  UnblockPickup | 100% | 72.6 | 100% | 55.02 | 24% |
|  GoToSeq | 100% | 87.81 | 100% | 70.39 | 20% |
|  Synth | 100% | 67.43 | 100% | 52.1 | 23% |
|  SynthLoc | 100% | 64.27 | 100% | 47.8 | 26% |
|  SynthSeq | 98.60% | 102 | 100% | 84.28 | 17% |
|  BossLevel | 98.60% | 109.21 | 100% | 89.57 | 18% |
|  BossLevel (2000 more runs) |  |  | 100% | 87.05 |  |
|  **On average** |  | 70.44235294117648 |  | 55.42058823529411 | 21% |

### CODE REVIEW

**Comment by maximecb** [comment]
I agree that you should fix the bot using access that the agent shouldn't have access to, that seems crucial.

I'm not sure what you mean by keeping both bots or not. Your Bot and BotAdvisor implementations are two near-identical classes?

**Comment by saleml** [comment]
Should be okay now - The tests would pass if https://github.com/maximecb/gym-minigrid/pull/25 is merged

**Comment by maximecb** [comment]
I looked through everything, but this is a big PR so it's hard to evaluate everything rigorously. We will have to trust your empirical tests that validate that the new bot works correctly.

Can you add a comment clarifying the purpose of the `use_location` argument to the header comment of `find_matching_objs(self, env, use_location=True)` ?

**Comment by maximecb** [comment]
Modifications to the verifier look OK

Levelgen: `colors_of_locked_doors` could just be a local variable instead of a member of `self`, it seems. The `validate_instrs` method shouldn't have side-effects.

**Comment by maximecb** [comment]
Ok seems ready to merge :)

**Pull request merged**
